---
# OVHNodeClass defines OVHcloud-specific configuration for Karpenter nodes
apiVersion: karpenter.ovhcloud.sh/v1alpha1
kind: OVHNodeClass
metadata:
  name: default
spec:
  # OVHcloud Public Cloud Project ID (32 hex characters)
  serviceName: "your-project-id"  # Replace with your Project ID

  # MKS Cluster ID (optional - auto-detected from cluster)
  kubeId: "your-cluster-id"  # Replace with your Cluster ID or remove for auto-detection

  # OVHcloud region (optional - auto-detected from cluster)
  region: "EU-WEST-PAR"  # Replace with your region or remove for auto-detection

  # Reference to Secret containing OVH API credentials
  credentialsSecretRef:
    name: ovh-credentials
    namespace: karpenter

  # Optional: Enable monthly billing (cheaper for long-running nodes)
  # ⚠️ Only available on gen2 instances: b2, c2, d2, r2
  monthlyBilled: false

  # Optional: Enable anti-affinity (spreads nodes across hypervisors)
  # Note: Max 5 nodes per pool when enabled
  antiAffinity: false
