# Karpenter OVHcloud Demo - Namespace and Credentials Secret
# Usage: envsubst < 01-namespace-secret.yaml | kubectl apply -f -
#
# Required environment variables:
#   - OVH_APPLICATION_KEY
#   - OVH_APPLICATION_SECRET
#   - OVH_CONSUMER_KEY
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: karpenter
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/component: credentials
type: Opaque
stringData:
  applicationKey: "${OVH_APPLICATION_KEY}"
  applicationSecret: "${OVH_APPLICATION_SECRET}"
  consumerKey: "${OVH_CONSUMER_KEY}"
