# Karpenter OVHcloud Demo - Multi-Zone NodePool
# Usage: kubectl apply -f 08-nodepool-multizone.yaml
#
# This NodePool enables provisioning across multiple availability zones.
# Note: Only EU-WEST-PAR and EU-SOUTH-MIL have 3 AZs on OVHcloud.
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: multi-zone
spec:
  template:
    metadata:
      labels:
        demo: karpenter-ovhcloud
        ha: multi-zone
    spec:
      nodeClassRef:
        group: karpenter.ovhcloud.sh
        kind: OVHNodeClass
        name: default

      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - b3-8
            - b3-16

        # Enable all 3 availability zones
        # Format: {region}-a, {region}-b, {region}-c
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - eu-west-par-a
            - eu-west-par-b
            - eu-west-par-c

        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]

      expireAfter: 720h

  limits:
    cpu: 50
    memory: 100Gi

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 2m
